services:
  postfix:
    restart: 'always'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:25:25
      - 0.0.0.0:1025:25
    volumes:
      - ./keys:/keys
      - ./logs:/maillogs
      - ./transport_mailcatcher:/etc/postfix/transport
    logging:
      options:
        max-size: "50m"
        max-file: "500"

  mailcatcher:
    restart: 'always'
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
