version: '2.4'
services:
  server:
    restart: 'always'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:25:25
      - 0.0.0.0:1025:25
    volumes:
      - ./keys:/keys
      - ./logs/raw:/mailraw
      - ./logs/list:/maillist
    logging:
      options:
        max-size: "50m"
        max-file: "500"